[install]
is_configured = true
build = 1

[launcher]
author = Splunky AI Sales Engineer
description = Data Source Assessment dashboard and ATT&CK audit analysis for Splunk telemetry.
version = 0.6.0

[ui]
is_visible = true
label = DSA, Data Source Assessment

[package]
id = TA-attack-coverage-advisor
check_for_updates = false
