[install]
is_configured = true
build = 1

[launcher]
author = Splunky AI Sales Engineer
description = DSA++ Maturity Accelerator for PvP, risk, ES detections, MITRE, roadmap and sizing workshops.
version = 0.9.2

[ui]
is_visible = true
label = DSA++ Maturity Accelerator

[package]
id = TA-attack-coverage-advisor
check_for_updates = false
