[attack_coverage_data_sources]
filename = attack_coverage_data_sources.csv

[attack_coverage_detections]
filename = attack_coverage_detections.csv

[attack_coverage_detection_data_sources]
filename = attack_coverage_detection_data_sources.csv
